UKESM:
    - '(UKESM)'
NorESM2:
    - '(NorESM2)'
GISS:
    - '(GISS)'
CESM2:
    - '(CESM2)'
MIROC-SPRINTARS:
    - '(MIROC-SPRINTARS)'
EC-Earth3:
    - '(EC-Earth3)'
CanESM5:
    - '(CanESM5)'
MRI-ESM2:
    - '(MRI-ESM2)'