name: Post-Processing Issue
description: The formatting of the dataset is inconvenient or incompatible with other datasets, but the underlying variable data is unaffected.
title: "[Post-Processing Issue]: (INSERT TITLE HERE)"
labels: ["post-processing"]
body:
  - type: markdown
    attributes:
      value: |
        The formatting of the dataset is inconvenient or incompatible with other datasets, but the underlying variable data is unaffected.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: In a few sentences, describe the issue.
      placeholder: ... post processing issue ...
    validations:
      required: true
  - type: dropdown
    id: models
    attributes:
      label: Models Impacted
      multiple: true
      description: Which models were impacted?
      options:
        - All models
        - UKESM
        - NorESM2
        - GISS
        - CESM2
        - MIROC-SPRINTARS
        - EC-Earth3
        - CanESM5
        - MRI-ESM2
    validations:
      required: true
  - type: dropdown
    id: experiments
    attributes:
      label: Which experiments were impacted?
      multiple: true
      options:
        - All experiments
        - All tier 1 transient experiments
        - All tier 2 transient experiments
        - All fixed-SST experiments
        - (Tier 1) ssp370
        - (Tier 1) ssp370-126aer
        - (Tier 1) ssp370-AFR126aer
        - (Tier 1) ssp370-EAS126aer
        - (Tier 1) ssp370-NAE126aer
        - (Tier 1) ssp370-SAS126aer
        - (Tier 2) ssp370-ASIA126aer
        - (Tier 2) ssp370-SAF126ca
        - (Tier 2) ssp370-SAS126ca
        - (Tier 2) ssp370-126aer_nh3nox
        - (Fixed-SST) piClim-370
        - (Fixed-SST) piClim-370-126aer
        - (Fixed-SST) piClim-370-AFR126aer
        - (Fixed-SST) piClim-370-EAS126aer
        - (Fixed-SST) piClim-370-NAE126aer
        - (Fixed-SST) piClim-370-SAS126aer
        - (Fixed-SST) piClim-370-126aer_nh3nox
    validations:
      required: true
  - type: textarea
    id: ensembles
    attributes:
      label: Ensemble Members
      description: Please indicate which ensemble members were impacted.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
    validations:
      required: true
  - type: textarea
    id: commentary
    attributes:
      label: Details
      description: Please describe the issue in detail including how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution (if you already have one)
      description: If you have a solution for this issue, please describe it hear. If not, no worries! The community will work towards developing one.
