name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[{"keywords": ["Model-UKESM"], "labels": ["UKESM"], "assignees": ["AgentOxygen"]}, {"keywords": ["Model-NorESM2"], "labels": ["NorESM2"], "assignees": ["AgentOxygen"]}, {"keywords": ["Model-GISS"], "labels": ["GISS"], "assignees": ["dmw2166", "tsigarid"]}, {"keywords": ["Model-CESM2"], "labels": ["CESM2"], "assignees": ["rjallen417"]}, {"keywords": ["Model-MIROC-SPRINTARS"], "labels": ["MIROC-SPRINTARS"], "assignees": ["AgentOxygen"]}, {"keywords": ["Model-EC-Earth3"], "labels": ["EC-Earth3"], "assignees": ["declan-FMI"]}, {"keywords": ["Model-CanESM5"], "labels": ["CanESM5"], "assignees": ["lfraserleach"]}, {"keywords": ["Model-MRI-ESM2"], "labels": ["MRI-ESM2"], "assignees": ["AgentOxygen"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
